---
title: "K562_MCF7_analysis"
output: html_document
date: "2024-08-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash}
#find the longgf results
#grep SumGF /bioinformatics/ryley/LongGF.run.MCF7_PacBio_SRX905986.log > /bioinformatics/ryley/LongGF.MCF7_PacBio_SRX905986.tsv

grep SumGF /bioinformatics/ryley/fusion_calling/LongGF*K562*ENCODE*.log > /bioinformatics/ryley/LongGF.K562.PacBio.tsv
grep SumGF /bioinformatics/ryley/fusion_calling/LongGF*SGNex*K562*.log > /bioinformatics/ryley/LongGF.K562.Nanopore.tsv
grep SumGF /bioinformatics/ryley/fusion_calling/LongGF*SGNex*MCF7*.log > /bioinformatics/ryley/LongGF.MCF7.Nanopore.tsv
grep SumGF /bioinformatics/ryley/fusion_calling/LongGF*MCF7*ENCODE*.log > /bioinformatics/ryley/LongGF.MCF7.PacBio.tsv

grep SumGF /bioinformatics/ryley/fusion_calling/LongGF*MCF7*ENCODE*.log
```

```{r}
library(tidyverse)
library(dplyr)
library(biomaRt)
library(ggplot2)
library(ggforce)
library(UpSetR)
library(ComplexUpset)
```
```{r}
known_fusions <- read.table("~/benchmark_data_analysis/real_gene_fusions.tsv", header=TRUE)
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
```

```{r}
####Read in Data
#LongGF
my_files <- list.files(path = "/bioinformatics/ryley", pattern = "LongGF", full.names=TRUE)
all_tsv <-lapply(my_files, read.table)
names(all_tsv) <- gsub(".tsv","",list.files(path = "/bioinformatics/ryley", pattern = "LongGF",full.names = FALSE),fixed = TRUE)
names <- gsub(".tsv","", list.files(path = "/bioinformatics/ryley", pattern = "LongGF",full.names = FALSE),fixed = TRUE)
df <- as.data.frame(all_csv$nameofyourfilename)
for(i in names){
  assign(i, read.table(paste0("/bioinformatics/ryley/", i, ".tsv")))
}
my_files <- list.files(path = "/bioinformatics/ryley", pattern = "LongGF", full.names=TRUE)
LongGF <- do.call(rbind, lapply(my_files, function(filename) {
  read.table(filename) %>%
    mutate(Source = basename(filename))
}))

LongGF$V1[LongGF$V1=="SumGF"] <- "/bioinformatics/ryley/fusion_calling/LongGF.run.MCF7_ENCODE_ENCFF887DGG_PacBio.log:SumGF"
#Genion
myfiles<- list.files(path = "/bioinformatics/ryley/fusion_calling", pattern = "*_genion\\.tsv$", full.names = TRUE)
file_list <- myfiles[!grepl("SRX905986", myfiles)]
Genion<- do.call(rbind, lapply(file_list, function(filename) {
  if (file.info(filename)$size > 0) {
    read.table(filename) %>%
      mutate(Source = basename(filename))
  } else {
    NULL
  }
}))


myfiles<- list.files(path = "/bioinformatics/ryley/fusion_calling", pattern = "K562.*_genion\\.tsv$", full.names = TRUE)
file_list <- myfiles[!grepl("PacBio", myfiles)]
genion_K562_Nanopore <- do.call(rbind, lapply(file_list, function(filename) {
  read.table(filename) %>%
    mutate(Source = basename(filename))
}))

file_list <- myfiles[!grepl("SGNex", myfiles)]
genion_K562_PacBio <-  do.call(rbind, lapply(file_list, function(filename) {
  read.table(filename) %>%
    mutate(Source = basename(filename))
}))
  
myfiles<-list.files(path = "/bioinformatics/ryley/fusion_calling", pattern = "MCF.*_genion\\.tsv$", full.names = TRUE)
file_list <- myfiles[!grepl("PacBio", myfiles)]
genion_MCF7_Nanopore <- do.call(rbind, lapply(file_list, function(filename) {
  if (file.info(filename)$size > 0) {
    read.table(filename) %>%
      mutate(Source = basename(filename))
  } else {
    NULL
  }
}))

file_list <- myfiles[!grepl("SGNex|SRX905986", myfiles)]
genion_MCF7_PacBio <- do.call(rbind, lapply(file_list, function(filename) {
  if (file.info(filename)$size > 0) {
    read.table(filename) %>%
      mutate(Source = basename(filename))
  } else {
    NULL
  }
}))  

#JAFFAL
myfiles<-list.files(path = "/bioinformatics/ryley/fusion_calling", pattern = "jaffa_results.csv", full.names = TRUE, recursive = TRUE)
file_list <- myfiles[!grepl("sim|05Feb24|SRX905986", myfiles)]
JAFFAL <-  do.call(rbind, lapply(file_list, function(filename) {
  read.table(filename, header = TRUE, sep = ",") %>%
    mutate(Source = basename(dirname(filename)))
}))

JAFFAL_K562_PacBio <- JAFFAL[grepl("PacBio", JAFFAL$sample, ignore.case = TRUE) & grepl("K562", JAFFAL$sample, ignore.case = TRUE), ]
JAFFAL_K562_Nanopore <- JAFFAL[!grepl("PacBio", JAFFAL$sample, ignore.case = TRUE) & grepl("K562", JAFFAL$sample, ignore.case = TRUE), ]
JAFFAL_MCF7_PacBio <- JAFFAL[grepl("PacBio", JAFFAL$sample, ignore.case = TRUE) & grepl("MCF", JAFFAL$sample, ignore.case = TRUE), ]
JAFFAL_MCF7_Nanopore <- JAFFAL[!grepl("PacBio", JAFFAL$sample, ignore.case = TRUE) & grepl("MCF", JAFFAL$sample, ignore.case = TRUE), ]

#fusionseeker
myfiles<-list.files(path = "/bioinformatics/ryley/fusion_calling", pattern = "confident_genefusion.txt", full.names = TRUE, recursive = TRUE)
file_list <- myfiles[!grepl("sim|05Feb24|SRX905986", myfiles)]
FusionSeeker <-  do.call(rbind, lapply(file_list, function(filename) {
  read.table(filename, header = TRUE) %>%
    mutate(Source = basename(dirname(filename)))
}))

FusionSeeker_K562_PacBio <- FusionSeeker[grepl("PacBio", FusionSeeker$Source, ignore.case = TRUE) & grepl("K562", FusionSeeker$Source, ignore.case = TRUE), ]
FusionSeeker_K562_Nanopore <- FusionSeeker[!grepl("PacBio", FusionSeeker$Source, ignore.case = TRUE) & grepl("K562", FusionSeeker$Source, ignore.case = TRUE), ]
FusionSeeker_MCF7_PacBio <- FusionSeeker[grepl("PacBio", FusionSeeker$Source, ignore.case = TRUE) & grepl("MCF", FusionSeeker$Source, ignore.case = TRUE), ]
FusionSeeker_MCF7_Nanopore <- FusionSeeker[!grepl("PacBio", FusionSeeker$Source, ignore.case = TRUE) & grepl("MCF", FusionSeeker$Source, ignore.case = TRUE), ]
```

```{r}
#find impossible fusions chrM x genomic genes
mito_chimeras_FusionSeekerK562 <- rbind(mutate(subset(FusionSeeker_K562_PacBio, (Chrom1 == "chrM" & Chrom2 != "chrM") | (Chrom1 != "chrM" & Chrom2 == "chrM")), platform = "PacBio", cell = "K562" ), mutate(subset(FusionSeeker_K562_Nanopore, (Chrom1 == "chrM" & Chrom2 != "chrM") | (Chrom1 != "chrM" & Chrom2 == "chrM")), platform = "Nanopore", cell = "K562" ))
mito_chimeras_FusionSeekerMCF7 <- rbind(mutate(subset(FusionSeeker_MCF7_PacBio, (Chrom1 == "chrM" & Chrom2 != "chrM") | (Chrom1 != "chrM" & Chrom2 == "chrM")), platform = "PacBio", cell = "MCF7" ), mutate(subset(FusionSeeker_MCF7_Nanopore, (Chrom1 == "chrM" & Chrom2 != "chrM") | (Chrom1 != "chrM" & Chrom2 == "chrM")), platform = "Nanopore", cell = "MCF7" ))

mito_chimeras_LongGFK562 <- rbind(mutate(filter(LongGF.K562.PacBio, (grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE)) | (!grepl("chrM:", V4, ignore.case = TRUE) & grepl("chrM:", V5, ignore.case = TRUE))), platform = "PacBio", cell = "K562" ), mutate(filter(LongGF.K562.Nanopore, (grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE)) | (!grepl("chrM:", V4, ignore.case = TRUE) & grepl("chrM:", V5, ignore.case = TRUE))) , platform = "Nanopore", cell = "K562" ))
mito_chimeras_LongGFMCF7 <- rbind(mutate(filter(LongGF.MCF7.PacBio, (grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE)) | (!grepl("chrM:", V4, ignore.case = TRUE) & grepl("chrM:", V5, ignore.case = TRUE))), platform = "PacBio", cell = "MCF7" ), mutate(filter(LongGF.MCF7.Nanopore, (grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE)) | (!grepl("chrM:", V4, ignore.case = TRUE) & grepl("chrM:", V5, ignore.case = TRUE))) , platform = "Nanopore", cell = "MCF7" ))

mito_chimeras_GENIONK562 <- rbind(filter(genion_K562_PacBio, grepl("M:", V8, ignore.case = TRUE)), filter(genion_K562_Nanopore, grepl("M:", V8, ignore.case = TRUE)))
mito_chimeras_GENIONMCF7 <- rbind(filter(genion_MCF7_PacBio, grepl("M:", V8, ignore.case = TRUE)), filter(genion_MCF7_Nanopore, grepl("M:", V8, ignore.case = TRUE)))

mito_chimeras_JAFFALK562 <- rbind(mutate(subset(JAFFAL_K562_PacBio, (chrom1 == "chrM" & chrom2 != "chrM") | (chrom1 != "chrM" & chrom2 == "chrM")), platform = "PacBio", cell = "K562" ), mutate(subset(JAFFAL_K562_Nanopore, (chrom1 == "chrM" & chrom2 != "chrM") | (chrom1 != "chrM" & chrom2 == "chrM")), platform = "Nanopore", cell = "K562" ))
mito_chimeras_JAFFALMCF7 <- rbind(mutate(subset(JAFFAL_MCF7_PacBio , (chrom1 == "chrM" & chrom2 != "chrM") | (chrom1 != "chrM" & chrom2 == "chrM")), platform = "PacBio", cell = "MCF7" ), mutate(subset(JAFFAL_MCF7_Nanopore, (chrom1 == "chrM" & chrom2 != "chrM") | (chrom1 != "chrM" & chrom2 == "chrM")), platform = "Nanopore", cell = "MCF7" ))

mito_chimeras <- rbind(mutate(rename(rbind(mito_chimeras_LongGFMCF7[c(3,(ncol(mito_chimeras_LongGFMCF7)-1) ,ncol(mito_chimeras_LongGFMCF7))], mito_chimeras_LongGFK562[c(3,(ncol(mito_chimeras_LongGFK562)-1) ,ncol(mito_chimeras_LongGFK562))]), "NumSupp"="V3"), Algorithm = "LongGF"), mutate(rbind(mito_chimeras_FusionSeekerK562[c(4, (ncol(mito_chimeras_FusionSeekerK562)-1), ncol(mito_chimeras_FusionSeekerK562))], mito_chimeras_FusionSeekerMCF7[c(4, (ncol(mito_chimeras_FusionSeekerMCF7)-1), ncol(mito_chimeras_FusionSeekerMCF7))]) , Algorithm = "FusionSeeker"))

ggplot(mito_chimeras, aes(x = NumSupp, fill = Algorithm)) + #, linetype = platform
  geom_density(alpha = 0.5) +
  theme_minimal() +
  labs(
    title = "Density Plot of impossible fusions detected",
    x = "Read Support") +
  scale_fill_brewer(palette = "Set1")+  # Optional: Customize color palette
 #scale_x_log10()+
  facet_zoom(xlim = c(1, 25))

ggplot(mito_chimeras, aes(x = NumSupp, fill = Algorithm)) + #, linetype = platform
  geom_density(alpha = 0.5) +
  theme_minimal() +
  labs(
    title = "Density Plot of impossible fusions detected",
    x = "Read Support") +
  scale_fill_brewer(palette = "Set1")+  # Optional: Customize color palette
 scale_x_log10()+
  facet_zoom(xlim = c(100, 300), ylim = c(0,0.5))

ggplot(mito_chimeras, aes(x = NumSupp))+
  geom_histogram(data = subset(mito_chimeras, Algorithm == "LongGF"), fill = 'red', alpha=0.5)+
  geom_histogram(data = subset(mito_chimeras, Algorithm == "FusionSeeker"), fill = 'blue', alpha=0.2)+
  scale_x_log10()

frequency_mito_chimeras <-  mito_chimeras %>%
  group_by_all %>%
  mutate(Frequency = n()) %>% unique()

ggplot((frequency_mito_chimeras), aes(x = NumSupp, y= Frequency, colour = Algorithm, shape = factor(platform)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Frequency of impossible fusions detected",
    x = "Read Support")

ggplot((frequency_mito_chimeras), aes(x = NumSupp, y= Frequency, colour = Algorithm, shape = factor(platform)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Frequency of impossible fusions detected",
    x = "Read Support")+
  scale_y_log10()

ggplot((frequency_mito_chimeras), aes(x = NumSupp, y= Frequency, colour = Algorithm, shape = factor(cell)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Frequency of impossible fusions detected",
    x = "Read Support")+
  facet_zoom(xlim = c(1, 100), ylim = c(0, 30))


```

```{r}
# removing impossible fusions from results

nomito_FusionSeekerK562 <- rbind(mutate(subset(FusionSeeker_K562_PacBio, (Chrom1 != "chrM" & Chrom2 != "chrM")), platform = "PacBio", cell = "K562" ), mutate(subset(FusionSeeker_K562_Nanopore, (Chrom1 != "chrM" & Chrom2 != "chrM")), platform = "Nanopore", cell = "K562" ))
nomito_FusionSeekerMCF7 <- rbind(mutate(subset(FusionSeeker_MCF7_PacBio, (Chrom1 != "chrM" & Chrom2 != "chrM")), platform = "PacBio", cell = "MCF7" ), mutate(subset(FusionSeeker_MCF7_Nanopore, (Chrom1 != "chrM" & Chrom2 != "chrM")), platform = "Nanopore", cell = "MCF7" ))

nomito_LongGFK562 <- rbind(mutate(filter(LongGF.K562.PacBio, (!grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE)) ), platform = "PacBio", cell = "K562" ), mutate(filter(LongGF.K562.Nanopore, (!grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE))) , platform = "Nanopore", cell = "K562" ))
nomito_LongGFMCF7 <- rbind(mutate(filter(LongGF.MCF7.PacBio, (!grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE)) ), platform = "PacBio", cell = "MCF7" ), mutate(filter(LongGF.MCF7.Nanopore, (!grepl("chrM:", V4, ignore.case = TRUE) & !grepl("chrM:", V5, ignore.case = TRUE))) , platform = "Nanopore", cell = "MCF7" ))

nomito_GENIONK562 <- rbind(mutate(filter(genion_K562_PacBio, !grepl("M:", V8, ignore.case = TRUE)), platform = "PacBio", cell = "K562"), mutate(filter(genion_K562_Nanopore, !grepl("M:", V8, ignore.case = TRUE)), platform = "Nanopore", cell = "K562"))
nomito_GENIONMCF7 <- rbind(mutate(filter(genion_MCF7_PacBio, !grepl("M:", V8, ignore.case = TRUE)), platform = "PacBio", cell = "MCF7"), mutate(filter(genion_MCF7_Nanopore, !grepl("M:", V8, ignore.case = TRUE)), platform = "Nanopore", cell = "MCF7"))

nomito_JAFFALK562 <- rbind(mutate(subset(JAFFAL_K562_PacBio, (chrom1 != "chrM" & chrom2 != "chrM")), platform = "PacBio", cell = "K562" ), mutate(subset(JAFFAL_K562_Nanopore, (chrom1 != "chrM" & chrom2 != "chrM")), platform = "Nanopore", cell = "K562" ))
nomito_JAFFALMCF7 <- rbind(mutate(subset(JAFFAL_MCF7_PacBio , (chrom1 != "chrM" & chrom2 != "chrM")), platform = "PacBio", cell = "MCF7" ), mutate(subset(JAFFAL_MCF7_Nanopore, (chrom1 != "chrM" & chrom2 != "chrM")), platform = "Nanopore", cell = "MCF7" ))

```

```{r}
#filter self-fusions
self_LongGFK562 <- nomito_LongGFK562 %>% separate(V2, into = c("V2.1","V2.2"), sep=":", remove = FALSE) %>%  subset(V2.1 == V2.2)
self_LongGFMCF7 <- nomito_LongGFMCF7 %>% separate(V2, into = c("V2.1","V2.2"), sep=":", remove = FALSE) %>%  subset(V2.1 == V2.2)

self_FusionSeekerK562 <- nomito_FusionSeekerK562 %>%
  subset((Gene1 == Gene2) | 
         mapply(grepl, pattern = paste0(Gene1, "_PAR_Y"), x = Gene2) | 
         mapply(grepl, pattern = paste0(Gene2, "_PAR_Y"), x = Gene1))
self_FusionSeekerMCF7 <- nomito_FusionSeekerMCF7 %>% subset((Gene1 == Gene2) | 
         mapply(grepl, pattern = paste0(Gene1, "_PAR_Y"), x = Gene2) | 
         mapply(grepl, pattern = paste0(Gene2, "_PAR_Y"), x = Gene1))

self_GENIONK562 <- nomito_GENIONK562 %>% separate(V1, into = c("V1.1","V1.2"), sep="::", remove = FALSE) %>%  subset((V1.1 == V1.2) | mapply(grepl, pattern = paste0(V1.1, "_PAR_Y"), x = V1.2) | 
         mapply(grepl, pattern = paste0(V1.2, "_PAR_Y"), x = V1.1))
self_GENIONKMCF7 <- nomito_GENIONMCF7 %>% separate(V1, into = c("V1.1","V1.2"), sep="::", remove = FALSE) %>%  subset((V1.1 == V1.2) | mapply(grepl, pattern = paste0(V1.1, "_PAR_Y"), x = V1.2) | 
         mapply(grepl, pattern = paste0(V1.2, "_PAR_Y"), x = V1.1))

self_JAFFALK562 <- nomito_JAFFALK562 %>% separate(fusion.genes, into = c("V1.1","V1.2"), sep=":", remove = FALSE) %>% subset(V1.1 == V1.2)
self_JAFFALMCF7 <- nomito_JAFFALMCF7 %>% separate(fusion.genes, into = c("V1.1","V1.2"), sep=":", remove = FALSE) %>%  subset(V1.1 == V1.2)

selfish <- rbind(mutate(rbind(self_LongGFK562, self_LongGFMCF7)[c(5, (ncol(self_LongGFK562)-1), ncol(self_LongGFK562))], Algorithm = "LongGF") , mutate(rename(rbind(self_FusionSeekerK562, self_FusionSeekerMCF7)[c(4, (ncol(self_FusionSeekerMCF7)-1), ncol(self_FusionSeekerMCF7))], "V3"="NumSupp"), Algorithm = "FusionSeeker")) %>%
  group_by_all %>%
  mutate(Frequency = n()) %>% unique()

ggplot((selfish), aes(x = V3, y= Frequency, colour = Algorithm, shape = factor(cell)))+
  geom_point(alpha = 0.5)+
  labs(title = "Frequency of self fusions",
    x = "Read Support")+
  facet_zoom(xlim = c(1, 25), ylim = c(0, 25))


```

```{r}
selfless_LongGFK562 <- nomito_LongGFK562 %>% separate(V2, into = c("V2.1","V2.2"), sep=":", remove = FALSE) %>%  subset(V2.1 != V2.2)
selfless_LongGFMCF7 <- nomito_LongGFMCF7 %>% separate(V2, into = c("V2.1","V2.2"), sep=":", remove = FALSE) %>%  subset(V2.1 != V2.2)

selfless_FusionSeekerK562 <- nomito_FusionSeekerK562 %>%
  subset((Gene1 != Gene2) &
         !mapply(grepl, pattern = paste0(Gene1, "_PAR_Y"), x = Gene2) & 
         !mapply(grepl, pattern = paste0(Gene2, "_PAR_Y"), x = Gene1))

selfless_FusionSeekerMCF7 <- nomito_FusionSeekerMCF7 %>% subset((Gene1 != Gene2) & 
         !mapply(grepl, pattern = paste0(Gene1, "_PAR_Y"), x = Gene2) & 
         !mapply(grepl, pattern = paste0(Gene2, "_PAR_Y"), x = Gene1))

selfless <- rbind(mutate(rename(rbind(selfless_LongGFMCF7[c(5,(ncol(selfless_LongGFMCF7)-1) ,ncol(selfless_LongGFMCF7))], selfless_LongGFK562[c(5,(ncol(selfless_LongGFK562)-1) ,ncol(selfless_LongGFK562))]), "NumSupp"="V3"), Algorithm = "LongGF"),
                  mutate(rbind(selfless_FusionSeekerK562[c(4, (ncol(selfless_FusionSeekerK562)-1), ncol(selfless_FusionSeekerK562))], selfless_FusionSeekerMCF7[c(4, (ncol(selfless_FusionSeekerMCF7)-1), ncol(selfless_FusionSeekerMCF7))]) , Algorithm = "FusionSeeker"),
                  rename(mutate(rbind(nomito_GENIONK562[c(5, (ncol(nomito_GENIONK562)-1), ncol(nomito_GENIONK562))], nomito_GENIONMCF7[c(5, (ncol(nomito_GENIONMCF7)-1), ncol(nomito_GENIONMCF7))]), Algorithm = "Genion"), "NumSupp"="V5"), 
                  mutate(rename(rbind(nomito_JAFFALK562[c(11, (ncol(nomito_JAFFALK562)-1), ncol(nomito_JAFFALK562))], nomito_JAFFALMCF7[c(11, (ncol(nomito_JAFFALMCF7)-1), ncol(nomito_JAFFALMCF7))]), "NumSupp"="spanning.reads"), Algorithm = "JAFFAL"))

frequency_selfless <- selfless %>%
  group_by_all %>%
  mutate(Frequency = n()) %>% unique()

ggplot(frequency_selfless, aes(x = NumSupp, y= Frequency, colour = Algorithm, shape = factor(cell)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Read Support of putative fusions",
    x = "Read Support",
    y= "count")+ 
  scale_y_log10()+
  scale_x_log10()


ggplot((subset(frequency_selfless, cell == "K562")), aes(x = NumSupp, y= Frequency, colour = Algorithm, shape = factor(platform)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Read Support of putative fusions in K562",
    x = "Read Support",
    y = "count")+ 
  scale_y_log10()+
  scale_x_log10()

ggplot((subset(frequency_selfless, cell == "MCF7")), aes(x = NumSupp, y= Frequency, colour = Algorithm, shape = factor(platform)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Read Support of putative fusions in MCF7",
    x = "Read Support")+ 
  scale_y_log10()+
  scale_x_log10()

ggplot((subset(selfless, cell == "MCF7")), aes(x = NumSupp, fill = Algorithm))+
  geom_density(alpha = 0.5)+
  labs(title = "Read Support of putative fusions in MCF7",
    x = "Read Support")+
  scale_x_log10()

ggplot((subset(selfless, cell == "MCF7")), aes(x = NumSupp, fill = Algorithm, after_stat(count)))+
  geom_density(alpha = 0.5 )+
  labs(title = "Read Support of putative fusions in MCF7",
    x = "Read Support")+
  scale_x_log10()+
  facet_zoom(xlim = c(1, 30), ylim = c(0,500))
```

```{r}
head(selfless_FusionSeekerK562[c(1:8, 10:12)])

consolidate_FusionSeekerK562<-selfless_FusionSeekerK562 %>%
  group_by(Gene1, Gene2, Chrom1, Chrom2, Source, platform, cell) %>%
  summarize(Total_NumSupp = sum(NumSupp))
consolidate_FusionSeekerMCF7<-selfless_FusionSeekerMCF7 %>%
  group_by(Gene1, Gene2, Chrom1, Chrom2, Source, platform, cell, ) %>%
  summarize(Total_NumSupp = sum(NumSupp))

consolidate_LongGFK562 <- selfless_LongGFK562 %>%
  group_by(V1,V2, V2.1, V2.2,  V4, V5, platform, cell) %>%
  summarize(Total_NumSupp = sum(V3))
consolidate_LongGFMCF7 <- selfless_LongGFMCF7 %>%
  group_by(V1,V2, V2.1, V2.2,  V4, V5, platform, cell) %>%
  summarize(Total_NumSupp = sum(V3))

consolidate_GENIONK562<- nomito_GENIONK562 %>%
  group_by(V1,V2, V3,  V4, V6, V7, Source, platform, cell) %>%
  summarize(Total_NumSupp = sum(V5))
consolidate_GENIONMCF7<- nomito_GENIONMCF7 %>%
  group_by(V1,V2, V3,  V4, V6, V7, Source, platform, cell) %>%
  summarize(Total_NumSupp = sum(V5))

consolidate_JAFFALK562<- nomito_JAFFALK562 %>%
  group_by(sample, fusion.genes, chrom1,  strand1, chrom2, strand2, Source, platform, cell) %>%
  summarize(Total_NumSupp = sum(spanning.reads))

consolidate_JAFFALMCF7 <- nomito_JAFFALMCF7 %>%
  group_by(sample, fusion.genes, chrom1,  strand1, chrom2, strand2, Source, platform, cell) %>%
  summarize(Total_NumSupp = sum(spanning.reads))

consolidated <- rbind(mutate(rbind(consolidate_LongGFK562, consolidate_LongGFMCF7)[c((ncol(consolidate_LongGFK562)-2): ncol(consolidate_LongGFK562))], Algorithm = "LongGF") , mutate(rbind(consolidate_FusionSeekerK562, consolidate_FusionSeekerMCF7)[c((ncol(consolidate_FusionSeekerMCF7)-2): ncol(consolidate_FusionSeekerMCF7))], Algorithm = "FusionSeeker"), mutate(rbind(consolidate_GENIONK562, consolidate_GENIONMCF7)[c((ncol(consolidate_GENIONK562)-2): ncol(consolidate_GENIONMCF7))], Algorithm = "Genion"), mutate(rbind(consolidate_JAFFALK562, consolidate_JAFFALMCF7)[c((ncol(consolidate_JAFFALK562)-2): ncol(consolidate_JAFFALK562))], Algorithm = "JAFFAL")) 

frequency_consolidated <- consolidated %>%
  group_by_all %>%
  mutate(Frequency = n()) %>% unique()

ggplot(frequency_consolidated, aes(x = Total_NumSupp, y= Frequency, colour = Algorithm, shape = factor(cell)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Read Support of putative fusions with consolidated breakpoints",
    x = "Read Support",
    y= "count")+ 
  scale_y_log10()+
  scale_x_log10()


```
```{r}
# Found Fusions overlap, ignoring source file and read support, only looking at cell lines

set1_JAFFALK562 <- gsub( ":", "::", c(consolidate_JAFFALK562$fusion.genes))
set2_GenionK562 <- c(consolidate_GENIONK562$V2)
set3_LongGFK562 <- gsub( ":", "::", c(consolidate_LongGFK562$V2))

#Adjust FusionSeeker dataset
set4_FusionSeekerK562 <- consolidate_FusionSeekerK562
set4_FusionSeekerK562$Gene1 <- gsub("\\..*", "", set4_FusionSeekerK562$Gene1)
set4_FusionSeekerK562$Gene2 <- gsub("\\..*", "", set4_FusionSeekerK562$Gene2)
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
gene_info_1 <- getBM(attributes = c("external_gene_name", "ensembl_gene_id", "chromosome_name"),
                             filters = "ensembl_gene_id",
                             values = unique(set4_FusionSeekerK562$Gene1),
                             mart = ensembl)
gene_info_2 <- getBM(attributes = c("external_gene_name", "ensembl_gene_id", "chromosome_name"),
                             filters = "ensembl_gene_id",
                             values = unique(set4_FusionSeekerK562$Gene2),
                             mart = ensembl)

set4_FusionSeekerK562 <- left_join(set4_FusionSeekerK562, gene_info_1, by=c("Gene1"="ensembl_gene_id")) %>%
  left_join(gene_info_2, by=c("Gene2"="ensembl_gene_id")) %>% 
  mutate( #Some gene IDs (often belonging to antisense genes) do not have an external name. so we replace the empty string with the gene id
    external_gene_name.x = coalesce(na_if(external_gene_name.x, ""), Gene1),
    external_gene_name.y = coalesce(na_if(external_gene_name.y, ""), Gene2)
  ) %>%
  unite(fusion.gene, c(external_gene_name.x, external_gene_name.y), sep = "::", remove = FALSE) %>%
  unite(fusion.gene.id, c(Gene1, Gene2), sep = "::", remove = FALSE)

length(unique(set1_JAFFALK562))
length(unique(set2_GenionK562))
length(unique(set3_LongGFK562))
length(unique(set4_FusionSeekerK562$fusion.gene))

Fusion_Gene_sets_K562 <- list(
  JAFFAL = unique(set1_JAFFALK562),
  Genion = unique(set2_GenionK562),
  LongGF = unique(set3_LongGFK562),
  FusionSeeker = unique(set4_FusionSeekerK562$fusion.gene),
  Known = subset(known_fusions, Cell_Line=="K562" , select=Known_Fusion)$Known_Fusion 
)

Tools <- colnames(fromList(Fusion_Gene_sets_K562)[1:4])
upset(fromList(Fusion_Gene_sets), sets = Tools, order.by = "degree") 
upset_fusion_results <- fromList(Fusion_Gene_sets_K562)

complex_upset_data <- fromList(Fusion_Gene_sets_K562)
complex_upset_data$Known <- complex_upset_data$Known %>% as.logical() #%>% factor(levels = c(TRUE, FALSE))
ComplexUpset::upset(complex_upset_data, 
      Tools, 
      #sort_intersections_by='degree',
      base_annotations=list('Found Fusions'=intersection_size(counts = TRUE, mapping = aes(fill=Known), ))
      ) 
```
```{r}
#Overall ReadSupport
Overall_JAFFALK562 <- consolidate_JAFFALK562 %>%
  group_by(fusion.genes, chrom1, chrom2, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp)) %>% mutate(Algorithm = "JAFFAL")
Overall_FusionSeekerK562 <- consolidate_FusionSeekerK562 %>%
  group_by(Gene1, Gene2, Chrom1, Chrom2, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp))%>% mutate(Algorithm = "FusionSeeker")
Overall_GENIONK562 <- consolidate_GENIONK562 %>%
  group_by(V2,  cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp))%>% mutate(Algorithm = "Genion")
Overall_LongGFK562 <- consolidate_LongGFK562 %>%
  group_by(V2, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp))%>% mutate(Algorithm = "LongGF")

Overall_JAFFALMCF7 <- consolidate_JAFFALMCF7 %>%
  group_by(fusion.genes, chrom1, chrom2, platform, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp)) %>% mutate(Algorithm = "JAFFAL")
Overall_FusionSeekerMCF7 <- consolidate_FusionSeekerMCF7 %>%
  group_by(Gene1, Gene2, Chrom1, Chrom2, platform, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp))%>% mutate(Algorithm = "FusionSeeker")
Overall_GENIONMCF7 <- consolidate_GENIONMCF7 %>%
  group_by(V2, platform, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp))%>% mutate(Algorithm = "Genion")
Overall_LongGFMCF7 <- consolidate_LongGFMCF7 %>%
  group_by(V2, platform, cell) %>%
  summarize(Overall_NumSupp = sum(Total_NumSupp))%>% mutate(Algorithm = "LongGF")

Overall_K562 <- rbind(Overall_JAFFALK562[c("cell","Overall_NumSupp","Algorithm")], Overall_FusionSeekerK562[c("cell","Overall_NumSupp","Algorithm")], Overall_GENIONK562[c("cell","Overall_NumSupp","Algorithm")], Overall_LongGFK562[c("cell","Overall_NumSupp","Algorithm")]) 


frequency_Overall_K562 <- Overall_K562 %>%
  group_by_all %>%
  mutate(Frequency = n()) %>% unique()

ggplot(frequency_Overall_K562, aes(x = Overall_NumSupp, y= Frequency, colour = Algorithm))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Read Support of putative fusions with consolidated breakpoints",
    x = "Read Support",
    y= "frequency")+ 
  scale_y_log10()+
  scale_x_log10()

ggplot((subset(Overall_K562, cell == "K562")), aes(x = Overall_NumSupp, fill = Algorithm))+
  geom_density(alpha = 0.5)+
  labs(title = "Read Support of putative fusions in K562",
    x = "Read Support")+
  scale_x_log10()

ggplot((subset(Overall_K562, cell == "K562")), aes(x = Overall_NumSupp, fill = Algorithm, after_stat(count)))+
  geom_density(alpha = 0.5)+
  labs(title = "Read Support of putative fusions in K562",
    x = "Read Support")+
  scale_x_log10()+
  facet_zoom(xlim=c(1,100), ylim=c(0,1500))

```
```{r}
#filter out overall = 1
Filt_Overall_JAFFALK562 <- Overall_JAFFALK562  %>% subset(Overall_NumSupp >1) 
Filt_Overall_GENIONK562 <- Overall_GENIONK562 %>% subset(Overall_NumSupp >1) 
Filt_Overall_LongGFK562 <- Overall_LongGFK562 %>% subset(Overall_NumSupp >1)
Filt_Overall_FusionSeekerK562 <- Overall_FusionSeekerK562  %>% subset(Overall_NumSupp >1)


#Adjust FusionSeeker dataset
Filt_Overall_FusionSeekerK562$Gene1 <- gsub("\\..*", "", Filt_Overall_FusionSeekerK562$Gene1)
Filt_Overall_FusionSeekerK562$Gene2 <- gsub("\\..*", "", Filt_Overall_FusionSeekerK562$Gene2)
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
gene_info_1 <- getBM(attributes = c("external_gene_name", "ensembl_gene_id", "chromosome_name"),
                             filters = "ensembl_gene_id",
                             values = unique(Filt_Overall_FusionSeekerK562$Gene1),
                             mart = ensembl)
gene_info_2 <- getBM(attributes = c("external_gene_name", "ensembl_gene_id", "chromosome_name"),
                             filters = "ensembl_gene_id",
                             values = unique(Filt_Overall_FusionSeekerK562$Gene2),
                             mart = ensembl)

Filt_Overall_FusionSeekerK562 <- left_join(Filt_Overall_FusionSeekerK562, gene_info_1, by=c("Gene1"="ensembl_gene_id")) %>%
  left_join(gene_info_2, by=c("Gene2"="ensembl_gene_id")) %>% 
  mutate( #Some gene IDs (often belonging to antisense genes) do not have an external name. so we replace the empty string with the gene id
    external_gene_name.x = coalesce(na_if(external_gene_name.x, ""), Gene1),
    external_gene_name.y = coalesce(na_if(external_gene_name.y, ""), Gene2)
  ) %>%
  unite(fusion.gene, c(external_gene_name.x, external_gene_name.y), sep = "::", remove = FALSE) %>%
  unite(fusion.gene.id, c(Gene1, Gene2), sep = "::", remove = FALSE)

Filt_Overall_FusionSeekerK562[c("cell", "Overall_NumSupp", "fusion.gene", "Algorithm")]


Fusion_Gene_sets_K562 <- list(
  JAFFAL = Filt_Overall_JAFFALK562$fusion.genes, #need to gsub the ::
  Genion = Filt_Overall_GENIONK562$V2,
  LongGF = Filt_Overall_LongGFK562$V2,
  FusionSeeker = Filt_Overall_FusionSeekerK562$fusion.gene,
  Known = subset(known_fusions, Cell_Line=="K562" , select=Known_Fusion)$Known_Fusion 
)

Tools <- colnames(fromList(Fusion_Gene_sets_K562)[1:4])
upset(fromList(Fusion_Gene_sets), sets = Tools, order.by = "degree") 
upset_fusion_results <- fromList(Fusion_Gene_sets_K562)

complex_upset_data <- fromList(Fusion_Gene_sets_K562)
complex_upset_data$Known <- complex_upset_data$Known %>% as.logical() #%>% factor(levels = c(TRUE, FALSE))
ComplexUpset::upset(complex_upset_data, 
      Tools, 
      #sort_intersections_by='degree',
      base_annotations=list('Found Fusions'=intersection_size(counts = TRUE, mapping = aes(fill=Known), ))
      ) 

```


