---
title: "simulated_reads_information"
output: html_document
date: '`r Sys.Date()`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{bash}
mkdir simulated_data_info/
scp jc462828@zodiac.hpc.jcu.edu.au:/gpfs01/v2/Q5401/Badread_Simulations_2024/fastq_files/false_positives.txt ./simulated_data_info/
scp jc462828@zodiac.hpc.jcu.edu.au:/gpfs01/v2/Q5401/Badread_Simulations_2024/fastq_files/true_positives.txt ./simulated_data_info/
scp jc462828@zodiac.hpc.jcu.edu.au:/gpfs01/v2/Q5401/Badread_Simulations_2024/fastq_files/simulated_bp_files.txt ./simulated_data_info/simulated_bp_files.txt
```
```{bash}
paste - - ./simulated_data_info/simulated_bp_files.txt ./simulated_data_info/bp_counts.txt
awk '
{
    if ($1 ~ /_1GB_/) {
        size = "1GB"
    } else if ($1 ~ /_10GB_/) {
        size = "10GB"
    } else if ($1 ~ /_100GB_/) {
        size = "100GB"
    }
    print $0, size
}' bp_counts.txt > table_with_size.txt
```
```{r}
library(ggplot2)
library(ggforce)
library(tidyr)
library(dplyr)
setwd("~/LongReadFusionCallerBenchmark/")
```
```{r}
read_depth<-  read.table('./simulated_data_info/bp_counts.txt')
ggplot(read_depth, aes(x = V3, y = V2, fill = V1, colour = V1))+
  geom_point()+
  scale_x_log10()+
  scale_y_log10()+
  xlab('Simulated Depth (GB)')+
  ylab('Counted bases')+
  ggtitle('Simulated Depth', subtitle = waiver())

ggplot(read_depth, aes(x = V3, y = V2, fill = V1, colour = V1))+
  geom_jitter()+
  scale_x_log10()+
  xlab('Depth (GB)')+
  ylab('Counted bases')+
  ggtitle('Simulated Depth', subtitle = waiver())

```
```{r}

false_positives <- read.table('./simulated_data_info/false_positives.txt') %>% mutate(V4 = "chimeras")
true_positives <- read.table('./simulated_data_info/true_positives.txt') %>% mutate(V4 = "fusions") %>% separate(V2, into = c('t1', 't2', 't3'), sep = "-", remove = FALSE)

temp_frame <- left_join(true_positives, simulated_fusions[c(1,3, 11)],by = c('t1'='name')) 
temp_frame <- temp_frame %>% left_join(simulated_fusions[c(1,3, 11)], by = c('t2'='name', 'fusionGene', 'fusionType')) %>% unique()
true_positives <- temp_frame %>% filter(!((is.na(t3) | t3 == "") & fusionType == "tri_fusion"))

inner_join( false_positives, simulated_fusions[1], by = c("V2" = "fusionGene")) #this code doesn't work, but it shows there are partial matches(1 gene shared) between false and simulated fusions

#extracting read counts of spiked in fusions
Positive_control_fusions <- true_positives[grep("Spike", true_positives$V1), ]
Negative_control_fusions <- anti_join(true_positives, Positive_control_fusions , by = 'V1')
#extracting read counts of simulated false chimeras
Positive_control_chimeras <- false_positives[grep("Spike", false_positives$V1), ]
Negative_control_chimeras <- anti_join(false_positives, Positive_control_chimeras,  by = 'V1')

# Rename columns to match
names(Negative_control_chimeras) <- names(Negative_control_fusions[c(1, 8, 6, 7)])
names(Positive_control_chimeras) <- names(Positive_control_fusions[c(1, 8, 6, 7)])
NC <- rbind(Negative_control_fusions[c(1, 8, 6,7)], Negative_control_chimeras)
PC <- rbind(Positive_control_fusions[c(1, 8, 6,7)], Positive_control_chimeras)

```

```{r}
#Negative Control
ggplot(filter(NC, V3 > 0), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5, binwidth=1,boundary=-0.5)+ 
  guides(fill = guide_legend(title = ""),
         colour = guide_legend(title = ""))+
  ylab('Count')+
  xlab('Read Support')+
  ggtitle('Simulated Negative Control', subtitle = waiver())+
  scale_x_continuous(breaks=1:96)

ggplot(filter(NC, V3 > 0), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5, binwidth=1,boundary=-0.5)+ 
  guides(fill = guide_legend(title = ""),
         colour = guide_legend(title = ""))+
  ylab('Count')+
  xlab('Read Support')+
  ggtitle('Simulated Negative Control', subtitle = waiver())+
  facet_zoom(xlim = c(0,5))+
  scale_x_continuous(expand = c(0, 0))

ggplot(filter(NC, V3 > 0), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5, binwidth=1,boundary=-0.5)+ 
  guides(fill = guide_legend(title = ""),
         colour = guide_legend(title = ""))+
  ylab('Count')+
  xlab('Read Support')+
  ggtitle('Simulated Negative Control', subtitle = waiver())+
  scale_x_log10()
```

```{r}
#Positive Control # need to subset by file
ggplot(filter(PC, V3 > 0), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5)+ 
  guides(fill = guide_legend(title = ""),colour = guide_legend(title = ""))+
  xlab('Read Support')+
  ylab('Count')+
  ggtitle('Simulated Positive Control', subtitle = waiver())+
  scale_y_log10()

ggplot(filter(PC, V3 > 0), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5)+ 
  guides(fill = guide_legend(title = ""),colour = guide_legend(title = ""))+
  xlab('Read Support')+
  ylab('Count')+
  ggtitle('Simulated Positive Control', subtitle = waiver())+
  scale_x_continuous(breaks=c(1:10, 1000, 2000, 3000, 4000))

ggplot(filter(PC, V3 > 0), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5, breaks = seq(0, 500, by = 5))+ 
  guides(fill = guide_legend(title = ""),colour = guide_legend(title = ""))+
  xlab('Read Support')+
  ylab('Count')+
  ggtitle('Simulated Positive Control', subtitle = waiver())+
  facet_zoom(xlim = c(0,100) ,ylim = c(0, 1500))

plot_list <- list()
for (depth in c("1GB", "10GB", "100GB")) {
  p <- ggplot(filter(PC[grep(depth, PC$V1), ]), aes(x = V3, fill = V4, colour = V4)) + 
  geom_histogram(alpha = 0.5, breaks = seq(0, 500, by = 5))+ 
  guides(fill = guide_legend(title = ""),colour = guide_legend(title = ""))+
  xlab('Read Support')+
  ylab('Count')+
  ggtitle('Simulated Positive Control', subtitle = waiver())+
  facet_zoom(xlim = c(0,100) ,ylim = c(0, 1500))
   plot_list[[depth]] <- p
}

plot_list[["1GB"]]
plot_list[["10GB"]]
plot_list[["100GB"]]
PC[grep("1GB", PC$V1), ]
```

